/**
 * Vericred API
 * Vericred's API allows you to search for Health Plans that a specific doctor
accepts.

## Getting Started

Visit our [Developer Portal](https://vericred.3scale.net) to
create an account.

Once you have created an account, you can create one Application for
Production and another for our Sandbox (select the appropriate Plan when
you create the Application).

## Authentication

To authenticate, pass the API Key you created in the Developer Portal as
a `Vericred-Api-Key` header.

`curl -H 'Vericred-Api-Key: YOUR_KEY' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Versioning

Vericred's API default to the latest version.  However, if you need a specific
version, you can request it with an `Accept-Version` header.

The current version is `v3`.  Previous versions are `v1` and `v2`.

`curl -H 'Vericred-Api-Key: YOUR_KEY' -H 'Accept-Version: v2' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Pagination

Endpoints that accept `page` and `per_page` parameters are paginated. They expose
four additional fields that contain data about your position in the response,
namely `Total`, `Per-Page`, `Link`, and `Page` as described in [RFC-5988](https://tools.ietf.org/html/rfc5988).

For example, to display 5 results per page and view the second page of a
`GET` to `/networks`, your final request would be `GET /networks?....page=2&per_page=5`.

## Sideloading

When we return multiple levels of an object graph (e.g. `Provider`s and their `State`s
we sideload the associated data.  In this example, we would provide an Array of
`State`s and a `state_id` for each provider.  This is done primarily to reduce the
payload size since many of the `Provider`s will share a `State`

```
{
  providers: [{ id: 1, state_id: 1}, { id: 2, state_id: 1 }],
  states: [{ id: 1, code: 'NY' }]
}
```

If you need the second level of the object graph, you can just match the
corresponding id.

## Selecting specific data

All endpoints allow you to specify which fields you would like to return.
This allows you to limit the response to contain only the data you need.

For example, let's take a request that returns the following JSON by default

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890',
    field_we_dont_care_about: 'value_we_dont_care_about'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY',
    field_we_dont_care_about: 'value_we_dont_care_about'
  }]
}
```

To limit our results to only return the fields we care about, we specify the
`select` query string parameter for the corresponding fields in the JSON
document.

In this case, we want to select `name` and `phone` from the `provider` key,
so we would add the parameters `select=provider.name,provider.phone`.
We also want the `name` and `code` from the `states` key, so we would
add the parameters `select=states.name,staes.code`.  The id field of
each document is always returned whether or not it is requested.

Our final request would be `GET /providers/12345?select=provider.name,provider.phone,states.name,states.code`

The response would be

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY'
  }]
}
```


 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.vericredClient) {
      root.vericredClient = {};
    }
    root.vericredClient.Provider = factory(root.vericredClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Provider model module.
   * @module model/Provider
   * @version 0.0.6
   */

  /**
   * Constructs a new <code>Provider</code>.
   * @alias module:model/Provider
   * @class
   */
  var exports = function() {
    var _this = this;





























  };

  /**
   * Constructs a <code>Provider</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Provider} obj Optional instance to populate.
   * @return {module:model/Provider} The populated <code>Provider</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('accepting_change_of_payor_patients')) {
        obj['accepting_change_of_payor_patients'] = ApiClient.convertToType(data['accepting_change_of_payor_patients'], 'Boolean');
      }
      if (data.hasOwnProperty('accepting_medicaid_patients')) {
        obj['accepting_medicaid_patients'] = ApiClient.convertToType(data['accepting_medicaid_patients'], 'Boolean');
      }
      if (data.hasOwnProperty('accepting_medicare_patients')) {
        obj['accepting_medicare_patients'] = ApiClient.convertToType(data['accepting_medicare_patients'], 'Boolean');
      }
      if (data.hasOwnProperty('accepting_private_patients')) {
        obj['accepting_private_patients'] = ApiClient.convertToType(data['accepting_private_patients'], 'Boolean');
      }
      if (data.hasOwnProperty('accepting_referral_patients')) {
        obj['accepting_referral_patients'] = ApiClient.convertToType(data['accepting_referral_patients'], 'Boolean');
      }
      if (data.hasOwnProperty('city')) {
        obj['city'] = ApiClient.convertToType(data['city'], 'String');
      }
      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('gender')) {
        obj['gender'] = ApiClient.convertToType(data['gender'], 'String');
      }
      if (data.hasOwnProperty('first_name')) {
        obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
      }
      if (data.hasOwnProperty('hios_ids')) {
        obj['hios_ids'] = ApiClient.convertToType(data['hios_ids'], ['String']);
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Integer');
      }
      if (data.hasOwnProperty('last_name')) {
        obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
      }
      if (data.hasOwnProperty('latitude')) {
        obj['latitude'] = ApiClient.convertToType(data['latitude'], 'Number');
      }
      if (data.hasOwnProperty('longitude')) {
        obj['longitude'] = ApiClient.convertToType(data['longitude'], 'Number');
      }
      if (data.hasOwnProperty('middle_name')) {
        obj['middle_name'] = ApiClient.convertToType(data['middle_name'], 'String');
      }
      if (data.hasOwnProperty('network_ids')) {
        obj['network_ids'] = ApiClient.convertToType(data['network_ids'], ['Integer']);
      }
      if (data.hasOwnProperty('personal_phone')) {
        obj['personal_phone'] = ApiClient.convertToType(data['personal_phone'], 'String');
      }
      if (data.hasOwnProperty('phone')) {
        obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
      }
      if (data.hasOwnProperty('presentation_name')) {
        obj['presentation_name'] = ApiClient.convertToType(data['presentation_name'], 'String');
      }
      if (data.hasOwnProperty('specialty')) {
        obj['specialty'] = ApiClient.convertToType(data['specialty'], 'String');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('state_id')) {
        obj['state_id'] = ApiClient.convertToType(data['state_id'], 'Integer');
      }
      if (data.hasOwnProperty('street_line_1')) {
        obj['street_line_1'] = ApiClient.convertToType(data['street_line_1'], 'String');
      }
      if (data.hasOwnProperty('street_line_2')) {
        obj['street_line_2'] = ApiClient.convertToType(data['street_line_2'], 'String');
      }
      if (data.hasOwnProperty('suffix')) {
        obj['suffix'] = ApiClient.convertToType(data['suffix'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('zip_code')) {
        obj['zip_code'] = ApiClient.convertToType(data['zip_code'], 'String');
      }
    }
    return obj;
  }

  /**
   * Is this provider accepting patients with a change of insurance?
   * @member {Boolean} accepting_change_of_payor_patients
   */
  exports.prototype['accepting_change_of_payor_patients'] = undefined;
  /**
   * Is this provider accepting new Medicaid patients?
   * @member {Boolean} accepting_medicaid_patients
   */
  exports.prototype['accepting_medicaid_patients'] = undefined;
  /**
   * Is this provider accepting new Medicare patients?
   * @member {Boolean} accepting_medicare_patients
   */
  exports.prototype['accepting_medicare_patients'] = undefined;
  /**
   * Is this provider accepting new patients with private insurance?
   * @member {Boolean} accepting_private_patients
   */
  exports.prototype['accepting_private_patients'] = undefined;
  /**
   * Is this provider accepting new patients via referrals?
   * @member {Boolean} accepting_referral_patients
   */
  exports.prototype['accepting_referral_patients'] = undefined;
  /**
   * City name (e.g. Springfield).
   * @member {String} city
   */
  exports.prototype['city'] = undefined;
  /**
   * Primary email address to contact the provider.
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * Provider's gender (M or F)
   * @member {String} gender
   */
  exports.prototype['gender'] = undefined;
  /**
   * Given name for the provider.
   * @member {String} first_name
   */
  exports.prototype['first_name'] = undefined;
  /**
   * List of HIOS ids for this provider
   * @member {Array.<String>} hios_ids
   */
  exports.prototype['hios_ids'] = undefined;
  /**
   * National Provider Index (NPI) number
   * @member {Integer} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Family name for the provider.
   * @member {String} last_name
   */
  exports.prototype['last_name'] = undefined;
  /**
   * Latitude of provider
   * @member {Number} latitude
   */
  exports.prototype['latitude'] = undefined;
  /**
   * Longitude of provider
   * @member {Number} longitude
   */
  exports.prototype['longitude'] = undefined;
  /**
   * Middle name for the provider.
   * @member {String} middle_name
   */
  exports.prototype['middle_name'] = undefined;
  /**
   * Array of network ids
   * @member {Array.<Integer>} network_ids
   */
  exports.prototype['network_ids'] = undefined;
  /**
   * Personal contact phone for the provider.
   * @member {String} personal_phone
   */
  exports.prototype['personal_phone'] = undefined;
  /**
   * Office phone for the provider
   * @member {String} phone
   */
  exports.prototype['phone'] = undefined;
  /**
   * Preferred name for display (e.g. Dr. Francis White may prefer Dr. Frank White)
   * @member {String} presentation_name
   */
  exports.prototype['presentation_name'] = undefined;
  /**
   * Name of the primary Specialty
   * @member {String} specialty
   */
  exports.prototype['specialty'] = undefined;
  /**
   * State code for the provider's address (e.g. NY).
   * @member {String} state
   */
  exports.prototype['state'] = undefined;
  /**
   * Foreign key to States
   * @member {Integer} state_id
   */
  exports.prototype['state_id'] = undefined;
  /**
   * First line of the provider's street address.
   * @member {String} street_line_1
   */
  exports.prototype['street_line_1'] = undefined;
  /**
   * Second line of the provider's street address.
   * @member {String} street_line_2
   */
  exports.prototype['street_line_2'] = undefined;
  /**
   * Suffix for the provider's name (e.g. Jr)
   * @member {String} suffix
   */
  exports.prototype['suffix'] = undefined;
  /**
   * Professional title for the provider (e.g. Dr).
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * Type of NPI number (individual provider vs organization).
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * Postal code for the provider's address (e.g. 11215)
   * @member {String} zip_code
   */
  exports.prototype['zip_code'] = undefined;




  return exports;
}));


