/**
 * Vericred API
 * Vericred's API allows you to search for Health Plans that a specific doctor
accepts.

## Getting Started

Visit our [Developer Portal](https://developers.vericred.com) to
create an account.

Once you have created an account, you can create one Application for
Production and another for our Sandbox (select the appropriate Plan when
you create the Application).

## SDKs

Our API follows standard REST conventions, so you can use any HTTP client
to integrate with us. You will likely find it easier to use one of our
[autogenerated SDKs](https://github.com/vericred/?query=vericred-),
which we make available for several common programming languages.

## Authentication

To authenticate, pass the API Key you created in the Developer Portal as
a `Vericred-Api-Key` header.

`curl -H 'Vericred-Api-Key: YOUR_KEY' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Versioning

Vericred's API default to the latest version.  However, if you need a specific
version, you can request it with an `Accept-Version` header.

The current version is `v3`.  Previous versions are `v1` and `v2`.

`curl -H 'Vericred-Api-Key: YOUR_KEY' -H 'Accept-Version: v2' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Pagination

Endpoints that accept `page` and `per_page` parameters are paginated. They expose
four additional fields that contain data about your position in the response,
namely `Total`, `Per-Page`, `Link`, and `Page` as described in [RFC-5988](https://tools.ietf.org/html/rfc5988).

For example, to display 5 results per page and view the second page of a
`GET` to `/networks`, your final request would be `GET /networks?....page=2&per_page=5`.

## Sideloading

When we return multiple levels of an object graph (e.g. `Provider`s and their `State`s
we sideload the associated data.  In this example, we would provide an Array of
`State`s and a `state_id` for each provider.  This is done primarily to reduce the
payload size since many of the `Provider`s will share a `State`

```
{
  providers: [{ id: 1, state_id: 1}, { id: 2, state_id: 1 }],
  states: [{ id: 1, code: 'NY' }]
}
```

If you need the second level of the object graph, you can just match the
corresponding id.

## Selecting specific data

All endpoints allow you to specify which fields you would like to return.
This allows you to limit the response to contain only the data you need.

For example, let's take a request that returns the following JSON by default

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890',
    field_we_dont_care_about: 'value_we_dont_care_about'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY',
    field_we_dont_care_about: 'value_we_dont_care_about'
  }]
}
```

To limit our results to only return the fields we care about, we specify the
`select` query string parameter for the corresponding fields in the JSON
document.

In this case, we want to select `name` and `phone` from the `provider` key,
so we would add the parameters `select=provider.name,provider.phone`.
We also want the `name` and `code` from the `states` key, so we would
add the parameters `select=states.name,states.code`.  The id field of
each document is always returned whether or not it is requested.

Our final request would be `GET /providers/12345?select=provider.name,provider.phone,states.name,states.code`

The response would be

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY'
  }]
}
```

## Benefits summary format
Benefit cost-share strings are formatted to capture:
 * Network tiers
 * Compound or conditional cost-share
 * Limits on the cost-share
 * Benefit-specific maximum out-of-pocket costs

**Example #1**
As an example, we would represent [this Summary of Benefits &amp; Coverage](https://s3.amazonaws.com/vericred-data/SBC/2017/33602TX0780032.pdf) as:

* **Hospital stay facility fees**:
  - Network Provider: `$400 copay/admit plus 20% coinsurance`
  - Out-of-Network Provider: `$1,500 copay/admit plus 50% coinsurance`
  - Vericred's format for this benefit: `In-Network: $400 before deductible then 20% after deductible / Out-of-Network: $1,500 before deductible then 50% after deductible`

* **Rehabilitation services:**
  - Network Provider: `20% coinsurance`
  - Out-of-Network Provider: `50% coinsurance`
  - Limitations & Exceptions: `35 visit maximum per benefit period combined with Chiropractic care.`
  - Vericred's format for this benefit: `In-Network: 20% after deductible / Out-of-Network: 50% after deductible | limit: 35 visit(s) per Benefit Period`

**Example #2**
In [this other Summary of Benefits &amp; Coverage](https://s3.amazonaws.com/vericred-data/SBC/2017/40733CA0110568.pdf), the **specialty_drugs** cost-share has a maximum out-of-pocket for in-network pharmacies.
* **Specialty drugs:**
  - Network Provider: `40% coinsurance up to a $500 maximum for up to a 30 day supply`
  - Out-of-Network Provider `Not covered`
  - Vericred's format for this benefit: `In-Network: 40% after deductible, up to $500 per script / Out-of-Network: 100%`

**BNF**

Here's a description of the benefits summary string, represented as a context-free grammar:

```
root                      ::= coverage

coverage                  ::= (simple_coverage | tiered_coverage) (space pipe space coverage_modifier)?
tiered_coverage           ::= tier (space slash space tier)*
tier                      ::= tier_name colon space (tier_coverage | not_applicable)
tier_coverage             ::= simple_coverage (space (then | or | and) space simple_coverage)* tier_limitation?
simple_coverage           ::= (pre_coverage_limitation space)? coverage_amount (space post_coverage_limitation)? (comma? space coverage_condition)?
coverage_modifier         ::= limit_condition colon space (((simple_coverage | simple_limitation) (semicolon space see_carrier_documentation)?) | see_carrier_documentation | waived_if_admitted | shared_across_tiers)
waived_if_admitted        ::= ("copay" space)? "waived if admitted"
simple_limitation         ::= pre_coverage_limitation space "copay applies"
tier_name                 ::= "In-Network-Tier-2" | "Out-of-Network" | "In-Network"
limit_condition           ::= "limit" | "condition"
tier_limitation           ::= comma space "up to" space (currency | (integer space time_unit plural?)) (space post_coverage_limitation)?
coverage_amount           ::= currency | unlimited | included | unknown | percentage | (digits space (treatment_unit | time_unit) plural?)
pre_coverage_limitation   ::= first space digits space time_unit plural?
post_coverage_limitation  ::= (((then space currency) | "per condition") space)? "per" space (treatment_unit | (integer space time_unit) | time_unit) plural?
coverage_condition        ::= ("before deductible" | "after deductible" | "penalty" | allowance | "in-state" | "out-of-state") (space allowance)?
allowance                 ::= upto_allowance | after_allowance
upto_allowance            ::= "up to" space (currency space)? "allowance"
after_allowance           ::= "after" space (currency space)? "allowance"
see_carrier_documentation ::= "see carrier documentation for more information"
shared_across_tiers       ::= "shared across all tiers"
unknown                   ::= "unknown"
unlimited                 ::= /[uU]nlimited/
included                  ::= /[iI]ncluded in [mM]edical/
time_unit                 ::= /[hH]our/ | (((/[cC]alendar/ | /[cC]ontract/) space)? /[yY]ear/) | /[mM]onth/ | /[dD]ay/ | /[wW]eek/ | /[vV]isit/ | /[lL]ifetime/ | ((((/[bB]enefit/ plural?) | /[eE]ligibility/) space)? /[pP]eriod/)
treatment_unit            ::= /[pP]erson/ | /[gG]roup/ | /[cC]ondition/ | /[sS]cript/ | /[vV]isit/ | /[eE]xam/ | /[iI]tem/ | /[sS]tay/ | /[tT]reatment/ | /[aA]dmission/ | /[eE]pisode/
comma                     ::= ","
colon                     ::= ":"
semicolon                 ::= ";"
pipe                      ::= "|"
slash                     ::= "/"
plural                    ::= "(s)" | "s"
then                      ::= "then" | ("," space) | space
or                        ::= "or"
and                       ::= "and"
not_applicable            ::= "Not Applicable" | "N/A" | "NA"
first                     ::= "first"
currency                  ::= "$" number
percentage                ::= number "%"
number                    ::= float | integer
float                     ::= digits "." digits
integer                   ::= /[0-9]/+ (comma_int | under_int)*
comma_int                 ::= ("," /[0-9]/*3) !"_"
under_int                 ::= ("_" /[0-9]/*3) !","
digits                    ::= /[0-9]/+ ("_" /[0-9]/+)*
space                     ::= /[ \t]/+
```


 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.vericredClient) {
      root.vericredClient = {};
    }
    root.vericredClient.RateRequest = factory(root.vericredClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RateRequest model module.
   * @module model/RateRequest
   * @version 0.0.11
   */

  /**
   * Constructs a new <code>RateRequest</code>.
   * @alias module:model/RateRequest
   * @class
   */
  var exports = function() {
    var _this = this;









































































































































  };

  /**
   * Constructs a <code>RateRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RateRequest} obj Optional instance to populate.
   * @return {module:model/RateRequest} The populated <code>RateRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('external_id')) {
        obj['external_id'] = ApiClient.convertToType(data['external_id'], 'String');
      }
      if (data.hasOwnProperty('effective_date')) {
        obj['effective_date'] = ApiClient.convertToType(data['effective_date'], 'String');
      }
      if (data.hasOwnProperty('expiration_date')) {
        obj['expiration_date'] = ApiClient.convertToType(data['expiration_date'], 'String');
      }
      if (data.hasOwnProperty('rating_area_natural_key')) {
        obj['rating_area_natural_key'] = ApiClient.convertToType(data['rating_area_natural_key'], 'String');
      }
      if (data.hasOwnProperty('age_0')) {
        obj['age_0'] = ApiClient.convertToType(data['age_0'], 'Number');
      }
      if (data.hasOwnProperty('age_0_tobacco')) {
        obj['age_0_tobacco'] = ApiClient.convertToType(data['age_0_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_1')) {
        obj['age_1'] = ApiClient.convertToType(data['age_1'], 'Number');
      }
      if (data.hasOwnProperty('age_1_tobacco')) {
        obj['age_1_tobacco'] = ApiClient.convertToType(data['age_1_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_2')) {
        obj['age_2'] = ApiClient.convertToType(data['age_2'], 'Number');
      }
      if (data.hasOwnProperty('age_2_tobacco')) {
        obj['age_2_tobacco'] = ApiClient.convertToType(data['age_2_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_3')) {
        obj['age_3'] = ApiClient.convertToType(data['age_3'], 'Number');
      }
      if (data.hasOwnProperty('age_3_tobacco')) {
        obj['age_3_tobacco'] = ApiClient.convertToType(data['age_3_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_4')) {
        obj['age_4'] = ApiClient.convertToType(data['age_4'], 'Number');
      }
      if (data.hasOwnProperty('age_4_tobacco')) {
        obj['age_4_tobacco'] = ApiClient.convertToType(data['age_4_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_5')) {
        obj['age_5'] = ApiClient.convertToType(data['age_5'], 'Number');
      }
      if (data.hasOwnProperty('age_5_tobacco')) {
        obj['age_5_tobacco'] = ApiClient.convertToType(data['age_5_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_6')) {
        obj['age_6'] = ApiClient.convertToType(data['age_6'], 'Number');
      }
      if (data.hasOwnProperty('age_6_tobacco')) {
        obj['age_6_tobacco'] = ApiClient.convertToType(data['age_6_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_7')) {
        obj['age_7'] = ApiClient.convertToType(data['age_7'], 'Number');
      }
      if (data.hasOwnProperty('age_7_tobacco')) {
        obj['age_7_tobacco'] = ApiClient.convertToType(data['age_7_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_8')) {
        obj['age_8'] = ApiClient.convertToType(data['age_8'], 'Number');
      }
      if (data.hasOwnProperty('age_8_tobacco')) {
        obj['age_8_tobacco'] = ApiClient.convertToType(data['age_8_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_9')) {
        obj['age_9'] = ApiClient.convertToType(data['age_9'], 'Number');
      }
      if (data.hasOwnProperty('age_9_tobacco')) {
        obj['age_9_tobacco'] = ApiClient.convertToType(data['age_9_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_10')) {
        obj['age_10'] = ApiClient.convertToType(data['age_10'], 'Number');
      }
      if (data.hasOwnProperty('age_10_tobacco')) {
        obj['age_10_tobacco'] = ApiClient.convertToType(data['age_10_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_11')) {
        obj['age_11'] = ApiClient.convertToType(data['age_11'], 'Number');
      }
      if (data.hasOwnProperty('age_11_tobacco')) {
        obj['age_11_tobacco'] = ApiClient.convertToType(data['age_11_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_12')) {
        obj['age_12'] = ApiClient.convertToType(data['age_12'], 'Number');
      }
      if (data.hasOwnProperty('age_12_tobacco')) {
        obj['age_12_tobacco'] = ApiClient.convertToType(data['age_12_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_13')) {
        obj['age_13'] = ApiClient.convertToType(data['age_13'], 'Number');
      }
      if (data.hasOwnProperty('age_13_tobacco')) {
        obj['age_13_tobacco'] = ApiClient.convertToType(data['age_13_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_14')) {
        obj['age_14'] = ApiClient.convertToType(data['age_14'], 'Number');
      }
      if (data.hasOwnProperty('age_14_tobacco')) {
        obj['age_14_tobacco'] = ApiClient.convertToType(data['age_14_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_15')) {
        obj['age_15'] = ApiClient.convertToType(data['age_15'], 'Number');
      }
      if (data.hasOwnProperty('age_15_tobacco')) {
        obj['age_15_tobacco'] = ApiClient.convertToType(data['age_15_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_16')) {
        obj['age_16'] = ApiClient.convertToType(data['age_16'], 'Number');
      }
      if (data.hasOwnProperty('age_16_tobacco')) {
        obj['age_16_tobacco'] = ApiClient.convertToType(data['age_16_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_17')) {
        obj['age_17'] = ApiClient.convertToType(data['age_17'], 'Number');
      }
      if (data.hasOwnProperty('age_17_tobacco')) {
        obj['age_17_tobacco'] = ApiClient.convertToType(data['age_17_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_18')) {
        obj['age_18'] = ApiClient.convertToType(data['age_18'], 'Number');
      }
      if (data.hasOwnProperty('age_18_tobacco')) {
        obj['age_18_tobacco'] = ApiClient.convertToType(data['age_18_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_19')) {
        obj['age_19'] = ApiClient.convertToType(data['age_19'], 'Number');
      }
      if (data.hasOwnProperty('age_19_tobacco')) {
        obj['age_19_tobacco'] = ApiClient.convertToType(data['age_19_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_20')) {
        obj['age_20'] = ApiClient.convertToType(data['age_20'], 'Number');
      }
      if (data.hasOwnProperty('age_20_tobacco')) {
        obj['age_20_tobacco'] = ApiClient.convertToType(data['age_20_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_21')) {
        obj['age_21'] = ApiClient.convertToType(data['age_21'], 'Number');
      }
      if (data.hasOwnProperty('age_21_tobacco')) {
        obj['age_21_tobacco'] = ApiClient.convertToType(data['age_21_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_22')) {
        obj['age_22'] = ApiClient.convertToType(data['age_22'], 'Number');
      }
      if (data.hasOwnProperty('age_22_tobacco')) {
        obj['age_22_tobacco'] = ApiClient.convertToType(data['age_22_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_23')) {
        obj['age_23'] = ApiClient.convertToType(data['age_23'], 'Number');
      }
      if (data.hasOwnProperty('age_23_tobacco')) {
        obj['age_23_tobacco'] = ApiClient.convertToType(data['age_23_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_24')) {
        obj['age_24'] = ApiClient.convertToType(data['age_24'], 'Number');
      }
      if (data.hasOwnProperty('age_24_tobacco')) {
        obj['age_24_tobacco'] = ApiClient.convertToType(data['age_24_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_25')) {
        obj['age_25'] = ApiClient.convertToType(data['age_25'], 'Number');
      }
      if (data.hasOwnProperty('age_25_tobacco')) {
        obj['age_25_tobacco'] = ApiClient.convertToType(data['age_25_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_26')) {
        obj['age_26'] = ApiClient.convertToType(data['age_26'], 'Number');
      }
      if (data.hasOwnProperty('age_26_tobacco')) {
        obj['age_26_tobacco'] = ApiClient.convertToType(data['age_26_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_27')) {
        obj['age_27'] = ApiClient.convertToType(data['age_27'], 'Number');
      }
      if (data.hasOwnProperty('age_27_tobacco')) {
        obj['age_27_tobacco'] = ApiClient.convertToType(data['age_27_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_28')) {
        obj['age_28'] = ApiClient.convertToType(data['age_28'], 'Number');
      }
      if (data.hasOwnProperty('age_28_tobacco')) {
        obj['age_28_tobacco'] = ApiClient.convertToType(data['age_28_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_29')) {
        obj['age_29'] = ApiClient.convertToType(data['age_29'], 'Number');
      }
      if (data.hasOwnProperty('age_29_tobacco')) {
        obj['age_29_tobacco'] = ApiClient.convertToType(data['age_29_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_30')) {
        obj['age_30'] = ApiClient.convertToType(data['age_30'], 'Number');
      }
      if (data.hasOwnProperty('age_30_tobacco')) {
        obj['age_30_tobacco'] = ApiClient.convertToType(data['age_30_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_31')) {
        obj['age_31'] = ApiClient.convertToType(data['age_31'], 'Number');
      }
      if (data.hasOwnProperty('age_31_tobacco')) {
        obj['age_31_tobacco'] = ApiClient.convertToType(data['age_31_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_32')) {
        obj['age_32'] = ApiClient.convertToType(data['age_32'], 'Number');
      }
      if (data.hasOwnProperty('age_32_tobacco')) {
        obj['age_32_tobacco'] = ApiClient.convertToType(data['age_32_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_33')) {
        obj['age_33'] = ApiClient.convertToType(data['age_33'], 'Number');
      }
      if (data.hasOwnProperty('age_33_tobacco')) {
        obj['age_33_tobacco'] = ApiClient.convertToType(data['age_33_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_34')) {
        obj['age_34'] = ApiClient.convertToType(data['age_34'], 'Number');
      }
      if (data.hasOwnProperty('age_34_tobacco')) {
        obj['age_34_tobacco'] = ApiClient.convertToType(data['age_34_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_35')) {
        obj['age_35'] = ApiClient.convertToType(data['age_35'], 'Number');
      }
      if (data.hasOwnProperty('age_35_tobacco')) {
        obj['age_35_tobacco'] = ApiClient.convertToType(data['age_35_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_36')) {
        obj['age_36'] = ApiClient.convertToType(data['age_36'], 'Number');
      }
      if (data.hasOwnProperty('age_36_tobacco')) {
        obj['age_36_tobacco'] = ApiClient.convertToType(data['age_36_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_37')) {
        obj['age_37'] = ApiClient.convertToType(data['age_37'], 'Number');
      }
      if (data.hasOwnProperty('age_37_tobacco')) {
        obj['age_37_tobacco'] = ApiClient.convertToType(data['age_37_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_38')) {
        obj['age_38'] = ApiClient.convertToType(data['age_38'], 'Number');
      }
      if (data.hasOwnProperty('age_38_tobacco')) {
        obj['age_38_tobacco'] = ApiClient.convertToType(data['age_38_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_39')) {
        obj['age_39'] = ApiClient.convertToType(data['age_39'], 'Number');
      }
      if (data.hasOwnProperty('age_39_tobacco')) {
        obj['age_39_tobacco'] = ApiClient.convertToType(data['age_39_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_40')) {
        obj['age_40'] = ApiClient.convertToType(data['age_40'], 'Number');
      }
      if (data.hasOwnProperty('age_40_tobacco')) {
        obj['age_40_tobacco'] = ApiClient.convertToType(data['age_40_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_41')) {
        obj['age_41'] = ApiClient.convertToType(data['age_41'], 'Number');
      }
      if (data.hasOwnProperty('age_41_tobacco')) {
        obj['age_41_tobacco'] = ApiClient.convertToType(data['age_41_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_42')) {
        obj['age_42'] = ApiClient.convertToType(data['age_42'], 'Number');
      }
      if (data.hasOwnProperty('age_42_tobacco')) {
        obj['age_42_tobacco'] = ApiClient.convertToType(data['age_42_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_43')) {
        obj['age_43'] = ApiClient.convertToType(data['age_43'], 'Number');
      }
      if (data.hasOwnProperty('age_43_tobacco')) {
        obj['age_43_tobacco'] = ApiClient.convertToType(data['age_43_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_44')) {
        obj['age_44'] = ApiClient.convertToType(data['age_44'], 'Number');
      }
      if (data.hasOwnProperty('age_44_tobacco')) {
        obj['age_44_tobacco'] = ApiClient.convertToType(data['age_44_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_45')) {
        obj['age_45'] = ApiClient.convertToType(data['age_45'], 'Number');
      }
      if (data.hasOwnProperty('age_45_tobacco')) {
        obj['age_45_tobacco'] = ApiClient.convertToType(data['age_45_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_46')) {
        obj['age_46'] = ApiClient.convertToType(data['age_46'], 'Number');
      }
      if (data.hasOwnProperty('age_46_tobacco')) {
        obj['age_46_tobacco'] = ApiClient.convertToType(data['age_46_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_47')) {
        obj['age_47'] = ApiClient.convertToType(data['age_47'], 'Number');
      }
      if (data.hasOwnProperty('age_47_tobacco')) {
        obj['age_47_tobacco'] = ApiClient.convertToType(data['age_47_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_48')) {
        obj['age_48'] = ApiClient.convertToType(data['age_48'], 'Number');
      }
      if (data.hasOwnProperty('age_48_tobacco')) {
        obj['age_48_tobacco'] = ApiClient.convertToType(data['age_48_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_49')) {
        obj['age_49'] = ApiClient.convertToType(data['age_49'], 'Number');
      }
      if (data.hasOwnProperty('age_49_tobacco')) {
        obj['age_49_tobacco'] = ApiClient.convertToType(data['age_49_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_50')) {
        obj['age_50'] = ApiClient.convertToType(data['age_50'], 'Number');
      }
      if (data.hasOwnProperty('age_50_tobacco')) {
        obj['age_50_tobacco'] = ApiClient.convertToType(data['age_50_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_51')) {
        obj['age_51'] = ApiClient.convertToType(data['age_51'], 'Number');
      }
      if (data.hasOwnProperty('age_51_tobacco')) {
        obj['age_51_tobacco'] = ApiClient.convertToType(data['age_51_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_52')) {
        obj['age_52'] = ApiClient.convertToType(data['age_52'], 'Number');
      }
      if (data.hasOwnProperty('age_52_tobacco')) {
        obj['age_52_tobacco'] = ApiClient.convertToType(data['age_52_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_53')) {
        obj['age_53'] = ApiClient.convertToType(data['age_53'], 'Number');
      }
      if (data.hasOwnProperty('age_53_tobacco')) {
        obj['age_53_tobacco'] = ApiClient.convertToType(data['age_53_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_54')) {
        obj['age_54'] = ApiClient.convertToType(data['age_54'], 'Number');
      }
      if (data.hasOwnProperty('age_54_tobacco')) {
        obj['age_54_tobacco'] = ApiClient.convertToType(data['age_54_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_55')) {
        obj['age_55'] = ApiClient.convertToType(data['age_55'], 'Number');
      }
      if (data.hasOwnProperty('age_55_tobacco')) {
        obj['age_55_tobacco'] = ApiClient.convertToType(data['age_55_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_56')) {
        obj['age_56'] = ApiClient.convertToType(data['age_56'], 'Number');
      }
      if (data.hasOwnProperty('age_56_tobacco')) {
        obj['age_56_tobacco'] = ApiClient.convertToType(data['age_56_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_57')) {
        obj['age_57'] = ApiClient.convertToType(data['age_57'], 'Number');
      }
      if (data.hasOwnProperty('age_57_tobacco')) {
        obj['age_57_tobacco'] = ApiClient.convertToType(data['age_57_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_58')) {
        obj['age_58'] = ApiClient.convertToType(data['age_58'], 'Number');
      }
      if (data.hasOwnProperty('age_58_tobacco')) {
        obj['age_58_tobacco'] = ApiClient.convertToType(data['age_58_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_59')) {
        obj['age_59'] = ApiClient.convertToType(data['age_59'], 'Number');
      }
      if (data.hasOwnProperty('age_59_tobacco')) {
        obj['age_59_tobacco'] = ApiClient.convertToType(data['age_59_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_60')) {
        obj['age_60'] = ApiClient.convertToType(data['age_60'], 'Number');
      }
      if (data.hasOwnProperty('age_60_tobacco')) {
        obj['age_60_tobacco'] = ApiClient.convertToType(data['age_60_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_61')) {
        obj['age_61'] = ApiClient.convertToType(data['age_61'], 'Number');
      }
      if (data.hasOwnProperty('age_61_tobacco')) {
        obj['age_61_tobacco'] = ApiClient.convertToType(data['age_61_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_62')) {
        obj['age_62'] = ApiClient.convertToType(data['age_62'], 'Number');
      }
      if (data.hasOwnProperty('age_62_tobacco')) {
        obj['age_62_tobacco'] = ApiClient.convertToType(data['age_62_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_63')) {
        obj['age_63'] = ApiClient.convertToType(data['age_63'], 'Number');
      }
      if (data.hasOwnProperty('age_63_tobacco')) {
        obj['age_63_tobacco'] = ApiClient.convertToType(data['age_63_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_64')) {
        obj['age_64'] = ApiClient.convertToType(data['age_64'], 'Number');
      }
      if (data.hasOwnProperty('age_64_tobacco')) {
        obj['age_64_tobacco'] = ApiClient.convertToType(data['age_64_tobacco'], 'Number');
      }
      if (data.hasOwnProperty('age_65')) {
        obj['age_65'] = ApiClient.convertToType(data['age_65'], 'Number');
      }
      if (data.hasOwnProperty('age_65_tobacco')) {
        obj['age_65_tobacco'] = ApiClient.convertToType(data['age_65_tobacco'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The external id of the plan
   * @member {String} external_id
   */
  exports.prototype['external_id'] = undefined;
  /**
   * The effective date of the rate
   * @member {String} effective_date
   */
  exports.prototype['effective_date'] = undefined;
  /**
   * The expiration date of the rate
   * @member {String} expiration_date
   */
  exports.prototype['expiration_date'] = undefined;
  /**
   * The natural key for the rating area of the  rate
   * @member {String} rating_area_natural_key
   */
  exports.prototype['rating_area_natural_key'] = undefined;
  /**
   * The age 0 non-tobacco rate for the plan
   * @member {Number} age_0
   */
  exports.prototype['age_0'] = undefined;
  /**
   * The age 0 tobacco rate for the plan
   * @member {Number} age_0_tobacco
   */
  exports.prototype['age_0_tobacco'] = undefined;
  /**
   * The age 1 non-tobacco rate for the plan
   * @member {Number} age_1
   */
  exports.prototype['age_1'] = undefined;
  /**
   * The age 1 tobacco rate for the plan
   * @member {Number} age_1_tobacco
   */
  exports.prototype['age_1_tobacco'] = undefined;
  /**
   * The age 2 non-tobacco rate for the plan
   * @member {Number} age_2
   */
  exports.prototype['age_2'] = undefined;
  /**
   * The age 2 tobacco rate for the plan
   * @member {Number} age_2_tobacco
   */
  exports.prototype['age_2_tobacco'] = undefined;
  /**
   * The age 3 non-tobacco rate for the plan
   * @member {Number} age_3
   */
  exports.prototype['age_3'] = undefined;
  /**
   * The age 3 tobacco rate for the plan
   * @member {Number} age_3_tobacco
   */
  exports.prototype['age_3_tobacco'] = undefined;
  /**
   * The age 4 non-tobacco rate for the plan
   * @member {Number} age_4
   */
  exports.prototype['age_4'] = undefined;
  /**
   * The age 4 tobacco rate for the plan
   * @member {Number} age_4_tobacco
   */
  exports.prototype['age_4_tobacco'] = undefined;
  /**
   * The age 5 non-tobacco rate for the plan
   * @member {Number} age_5
   */
  exports.prototype['age_5'] = undefined;
  /**
   * The age 5 tobacco rate for the plan
   * @member {Number} age_5_tobacco
   */
  exports.prototype['age_5_tobacco'] = undefined;
  /**
   * The age 6 non-tobacco rate for the plan
   * @member {Number} age_6
   */
  exports.prototype['age_6'] = undefined;
  /**
   * The age 6 tobacco rate for the plan
   * @member {Number} age_6_tobacco
   */
  exports.prototype['age_6_tobacco'] = undefined;
  /**
   * The age 7 non-tobacco rate for the plan
   * @member {Number} age_7
   */
  exports.prototype['age_7'] = undefined;
  /**
   * The age 7 tobacco rate for the plan
   * @member {Number} age_7_tobacco
   */
  exports.prototype['age_7_tobacco'] = undefined;
  /**
   * The age 8 non-tobacco rate for the plan
   * @member {Number} age_8
   */
  exports.prototype['age_8'] = undefined;
  /**
   * The age 8 tobacco rate for the plan
   * @member {Number} age_8_tobacco
   */
  exports.prototype['age_8_tobacco'] = undefined;
  /**
   * The age 9 non-tobacco rate for the plan
   * @member {Number} age_9
   */
  exports.prototype['age_9'] = undefined;
  /**
   * The age 9 tobacco rate for the plan
   * @member {Number} age_9_tobacco
   */
  exports.prototype['age_9_tobacco'] = undefined;
  /**
   * The age 10 non-tobacco rate for the plan
   * @member {Number} age_10
   */
  exports.prototype['age_10'] = undefined;
  /**
   * The age 10 tobacco rate for the plan
   * @member {Number} age_10_tobacco
   */
  exports.prototype['age_10_tobacco'] = undefined;
  /**
   * The age 11 non-tobacco rate for the plan
   * @member {Number} age_11
   */
  exports.prototype['age_11'] = undefined;
  /**
   * The age 11 tobacco rate for the plan
   * @member {Number} age_11_tobacco
   */
  exports.prototype['age_11_tobacco'] = undefined;
  /**
   * The age 12 non-tobacco rate for the plan
   * @member {Number} age_12
   */
  exports.prototype['age_12'] = undefined;
  /**
   * The age 12 tobacco rate for the plan
   * @member {Number} age_12_tobacco
   */
  exports.prototype['age_12_tobacco'] = undefined;
  /**
   * The age 13 non-tobacco rate for the plan
   * @member {Number} age_13
   */
  exports.prototype['age_13'] = undefined;
  /**
   * The age 13 tobacco rate for the plan
   * @member {Number} age_13_tobacco
   */
  exports.prototype['age_13_tobacco'] = undefined;
  /**
   * The age 14 non-tobacco rate for the plan
   * @member {Number} age_14
   */
  exports.prototype['age_14'] = undefined;
  /**
   * The age 14 tobacco rate for the plan
   * @member {Number} age_14_tobacco
   */
  exports.prototype['age_14_tobacco'] = undefined;
  /**
   * The age 15 non-tobacco rate for the plan
   * @member {Number} age_15
   */
  exports.prototype['age_15'] = undefined;
  /**
   * The age 15 tobacco rate for the plan
   * @member {Number} age_15_tobacco
   */
  exports.prototype['age_15_tobacco'] = undefined;
  /**
   * The age 16 non-tobacco rate for the plan
   * @member {Number} age_16
   */
  exports.prototype['age_16'] = undefined;
  /**
   * The age 16 tobacco rate for the plan
   * @member {Number} age_16_tobacco
   */
  exports.prototype['age_16_tobacco'] = undefined;
  /**
   * The age 17 non-tobacco rate for the plan
   * @member {Number} age_17
   */
  exports.prototype['age_17'] = undefined;
  /**
   * The age 17 tobacco rate for the plan
   * @member {Number} age_17_tobacco
   */
  exports.prototype['age_17_tobacco'] = undefined;
  /**
   * The age 18 non-tobacco rate for the plan
   * @member {Number} age_18
   */
  exports.prototype['age_18'] = undefined;
  /**
   * The age 18 tobacco rate for the plan
   * @member {Number} age_18_tobacco
   */
  exports.prototype['age_18_tobacco'] = undefined;
  /**
   * The age 19 non-tobacco rate for the plan
   * @member {Number} age_19
   */
  exports.prototype['age_19'] = undefined;
  /**
   * The age 19 tobacco rate for the plan
   * @member {Number} age_19_tobacco
   */
  exports.prototype['age_19_tobacco'] = undefined;
  /**
   * The age 20 non-tobacco rate for the plan
   * @member {Number} age_20
   */
  exports.prototype['age_20'] = undefined;
  /**
   * The age 20 tobacco rate for the plan
   * @member {Number} age_20_tobacco
   */
  exports.prototype['age_20_tobacco'] = undefined;
  /**
   * The age 21 non-tobacco rate for the plan
   * @member {Number} age_21
   */
  exports.prototype['age_21'] = undefined;
  /**
   * The age 21 tobacco rate for the plan
   * @member {Number} age_21_tobacco
   */
  exports.prototype['age_21_tobacco'] = undefined;
  /**
   * The age 22 non-tobacco rate for the plan
   * @member {Number} age_22
   */
  exports.prototype['age_22'] = undefined;
  /**
   * The age 22 tobacco rate for the plan
   * @member {Number} age_22_tobacco
   */
  exports.prototype['age_22_tobacco'] = undefined;
  /**
   * The age 23 non-tobacco rate for the plan
   * @member {Number} age_23
   */
  exports.prototype['age_23'] = undefined;
  /**
   * The age 23 tobacco rate for the plan
   * @member {Number} age_23_tobacco
   */
  exports.prototype['age_23_tobacco'] = undefined;
  /**
   * The age 24 non-tobacco rate for the plan
   * @member {Number} age_24
   */
  exports.prototype['age_24'] = undefined;
  /**
   * The age 24 tobacco rate for the plan
   * @member {Number} age_24_tobacco
   */
  exports.prototype['age_24_tobacco'] = undefined;
  /**
   * The age 25 non-tobacco rate for the plan
   * @member {Number} age_25
   */
  exports.prototype['age_25'] = undefined;
  /**
   * The age 25 tobacco rate for the plan
   * @member {Number} age_25_tobacco
   */
  exports.prototype['age_25_tobacco'] = undefined;
  /**
   * The age 26 non-tobacco rate for the plan
   * @member {Number} age_26
   */
  exports.prototype['age_26'] = undefined;
  /**
   * The age 26 tobacco rate for the plan
   * @member {Number} age_26_tobacco
   */
  exports.prototype['age_26_tobacco'] = undefined;
  /**
   * The age 27 non-tobacco rate for the plan
   * @member {Number} age_27
   */
  exports.prototype['age_27'] = undefined;
  /**
   * The age 27 tobacco rate for the plan
   * @member {Number} age_27_tobacco
   */
  exports.prototype['age_27_tobacco'] = undefined;
  /**
   * The age 28 non-tobacco rate for the plan
   * @member {Number} age_28
   */
  exports.prototype['age_28'] = undefined;
  /**
   * The age 28 tobacco rate for the plan
   * @member {Number} age_28_tobacco
   */
  exports.prototype['age_28_tobacco'] = undefined;
  /**
   * The age 29 non-tobacco rate for the plan
   * @member {Number} age_29
   */
  exports.prototype['age_29'] = undefined;
  /**
   * The age 29 tobacco rate for the plan
   * @member {Number} age_29_tobacco
   */
  exports.prototype['age_29_tobacco'] = undefined;
  /**
   * The age 30 non-tobacco rate for the plan
   * @member {Number} age_30
   */
  exports.prototype['age_30'] = undefined;
  /**
   * The age 30 tobacco rate for the plan
   * @member {Number} age_30_tobacco
   */
  exports.prototype['age_30_tobacco'] = undefined;
  /**
   * The age 31 non-tobacco rate for the plan
   * @member {Number} age_31
   */
  exports.prototype['age_31'] = undefined;
  /**
   * The age 31 tobacco rate for the plan
   * @member {Number} age_31_tobacco
   */
  exports.prototype['age_31_tobacco'] = undefined;
  /**
   * The age 32 non-tobacco rate for the plan
   * @member {Number} age_32
   */
  exports.prototype['age_32'] = undefined;
  /**
   * The age 32 tobacco rate for the plan
   * @member {Number} age_32_tobacco
   */
  exports.prototype['age_32_tobacco'] = undefined;
  /**
   * The age 33 non-tobacco rate for the plan
   * @member {Number} age_33
   */
  exports.prototype['age_33'] = undefined;
  /**
   * The age 33 tobacco rate for the plan
   * @member {Number} age_33_tobacco
   */
  exports.prototype['age_33_tobacco'] = undefined;
  /**
   * The age 34 non-tobacco rate for the plan
   * @member {Number} age_34
   */
  exports.prototype['age_34'] = undefined;
  /**
   * The age 34 tobacco rate for the plan
   * @member {Number} age_34_tobacco
   */
  exports.prototype['age_34_tobacco'] = undefined;
  /**
   * The age 35 non-tobacco rate for the plan
   * @member {Number} age_35
   */
  exports.prototype['age_35'] = undefined;
  /**
   * The age 35 tobacco rate for the plan
   * @member {Number} age_35_tobacco
   */
  exports.prototype['age_35_tobacco'] = undefined;
  /**
   * The age 36 non-tobacco rate for the plan
   * @member {Number} age_36
   */
  exports.prototype['age_36'] = undefined;
  /**
   * The age 36 tobacco rate for the plan
   * @member {Number} age_36_tobacco
   */
  exports.prototype['age_36_tobacco'] = undefined;
  /**
   * The age 37 non-tobacco rate for the plan
   * @member {Number} age_37
   */
  exports.prototype['age_37'] = undefined;
  /**
   * The age 37 tobacco rate for the plan
   * @member {Number} age_37_tobacco
   */
  exports.prototype['age_37_tobacco'] = undefined;
  /**
   * The age 38 non-tobacco rate for the plan
   * @member {Number} age_38
   */
  exports.prototype['age_38'] = undefined;
  /**
   * The age 38 tobacco rate for the plan
   * @member {Number} age_38_tobacco
   */
  exports.prototype['age_38_tobacco'] = undefined;
  /**
   * The age 39 non-tobacco rate for the plan
   * @member {Number} age_39
   */
  exports.prototype['age_39'] = undefined;
  /**
   * The age 39 tobacco rate for the plan
   * @member {Number} age_39_tobacco
   */
  exports.prototype['age_39_tobacco'] = undefined;
  /**
   * The age 40 non-tobacco rate for the plan
   * @member {Number} age_40
   */
  exports.prototype['age_40'] = undefined;
  /**
   * The age 40 tobacco rate for the plan
   * @member {Number} age_40_tobacco
   */
  exports.prototype['age_40_tobacco'] = undefined;
  /**
   * The age 41 non-tobacco rate for the plan
   * @member {Number} age_41
   */
  exports.prototype['age_41'] = undefined;
  /**
   * The age 41 tobacco rate for the plan
   * @member {Number} age_41_tobacco
   */
  exports.prototype['age_41_tobacco'] = undefined;
  /**
   * The age 42 non-tobacco rate for the plan
   * @member {Number} age_42
   */
  exports.prototype['age_42'] = undefined;
  /**
   * The age 42 tobacco rate for the plan
   * @member {Number} age_42_tobacco
   */
  exports.prototype['age_42_tobacco'] = undefined;
  /**
   * The age 43 non-tobacco rate for the plan
   * @member {Number} age_43
   */
  exports.prototype['age_43'] = undefined;
  /**
   * The age 43 tobacco rate for the plan
   * @member {Number} age_43_tobacco
   */
  exports.prototype['age_43_tobacco'] = undefined;
  /**
   * The age 44 non-tobacco rate for the plan
   * @member {Number} age_44
   */
  exports.prototype['age_44'] = undefined;
  /**
   * The age 44 tobacco rate for the plan
   * @member {Number} age_44_tobacco
   */
  exports.prototype['age_44_tobacco'] = undefined;
  /**
   * The age 45 non-tobacco rate for the plan
   * @member {Number} age_45
   */
  exports.prototype['age_45'] = undefined;
  /**
   * The age 45 tobacco rate for the plan
   * @member {Number} age_45_tobacco
   */
  exports.prototype['age_45_tobacco'] = undefined;
  /**
   * The age 46 non-tobacco rate for the plan
   * @member {Number} age_46
   */
  exports.prototype['age_46'] = undefined;
  /**
   * The age 46 tobacco rate for the plan
   * @member {Number} age_46_tobacco
   */
  exports.prototype['age_46_tobacco'] = undefined;
  /**
   * The age 47 non-tobacco rate for the plan
   * @member {Number} age_47
   */
  exports.prototype['age_47'] = undefined;
  /**
   * The age 47 tobacco rate for the plan
   * @member {Number} age_47_tobacco
   */
  exports.prototype['age_47_tobacco'] = undefined;
  /**
   * The age 48 non-tobacco rate for the plan
   * @member {Number} age_48
   */
  exports.prototype['age_48'] = undefined;
  /**
   * The age 48 tobacco rate for the plan
   * @member {Number} age_48_tobacco
   */
  exports.prototype['age_48_tobacco'] = undefined;
  /**
   * The age 49 non-tobacco rate for the plan
   * @member {Number} age_49
   */
  exports.prototype['age_49'] = undefined;
  /**
   * The age 49 tobacco rate for the plan
   * @member {Number} age_49_tobacco
   */
  exports.prototype['age_49_tobacco'] = undefined;
  /**
   * The age 50 non-tobacco rate for the plan
   * @member {Number} age_50
   */
  exports.prototype['age_50'] = undefined;
  /**
   * The age 50 tobacco rate for the plan
   * @member {Number} age_50_tobacco
   */
  exports.prototype['age_50_tobacco'] = undefined;
  /**
   * The age 51 non-tobacco rate for the plan
   * @member {Number} age_51
   */
  exports.prototype['age_51'] = undefined;
  /**
   * The age 51 tobacco rate for the plan
   * @member {Number} age_51_tobacco
   */
  exports.prototype['age_51_tobacco'] = undefined;
  /**
   * The age 52 non-tobacco rate for the plan
   * @member {Number} age_52
   */
  exports.prototype['age_52'] = undefined;
  /**
   * The age 52 tobacco rate for the plan
   * @member {Number} age_52_tobacco
   */
  exports.prototype['age_52_tobacco'] = undefined;
  /**
   * The age 53 non-tobacco rate for the plan
   * @member {Number} age_53
   */
  exports.prototype['age_53'] = undefined;
  /**
   * The age 53 tobacco rate for the plan
   * @member {Number} age_53_tobacco
   */
  exports.prototype['age_53_tobacco'] = undefined;
  /**
   * The age 54 non-tobacco rate for the plan
   * @member {Number} age_54
   */
  exports.prototype['age_54'] = undefined;
  /**
   * The age 54 tobacco rate for the plan
   * @member {Number} age_54_tobacco
   */
  exports.prototype['age_54_tobacco'] = undefined;
  /**
   * The age 55 non-tobacco rate for the plan
   * @member {Number} age_55
   */
  exports.prototype['age_55'] = undefined;
  /**
   * The age 55 tobacco rate for the plan
   * @member {Number} age_55_tobacco
   */
  exports.prototype['age_55_tobacco'] = undefined;
  /**
   * The age 56 non-tobacco rate for the plan
   * @member {Number} age_56
   */
  exports.prototype['age_56'] = undefined;
  /**
   * The age 56 tobacco rate for the plan
   * @member {Number} age_56_tobacco
   */
  exports.prototype['age_56_tobacco'] = undefined;
  /**
   * The age 57 non-tobacco rate for the plan
   * @member {Number} age_57
   */
  exports.prototype['age_57'] = undefined;
  /**
   * The age 57 tobacco rate for the plan
   * @member {Number} age_57_tobacco
   */
  exports.prototype['age_57_tobacco'] = undefined;
  /**
   * The age 58 non-tobacco rate for the plan
   * @member {Number} age_58
   */
  exports.prototype['age_58'] = undefined;
  /**
   * The age 58 tobacco rate for the plan
   * @member {Number} age_58_tobacco
   */
  exports.prototype['age_58_tobacco'] = undefined;
  /**
   * The age 59 non-tobacco rate for the plan
   * @member {Number} age_59
   */
  exports.prototype['age_59'] = undefined;
  /**
   * The age 59 tobacco rate for the plan
   * @member {Number} age_59_tobacco
   */
  exports.prototype['age_59_tobacco'] = undefined;
  /**
   * The age 60 non-tobacco rate for the plan
   * @member {Number} age_60
   */
  exports.prototype['age_60'] = undefined;
  /**
   * The age 60 tobacco rate for the plan
   * @member {Number} age_60_tobacco
   */
  exports.prototype['age_60_tobacco'] = undefined;
  /**
   * The age 61 non-tobacco rate for the plan
   * @member {Number} age_61
   */
  exports.prototype['age_61'] = undefined;
  /**
   * The age 61 tobacco rate for the plan
   * @member {Number} age_61_tobacco
   */
  exports.prototype['age_61_tobacco'] = undefined;
  /**
   * The age 62 non-tobacco rate for the plan
   * @member {Number} age_62
   */
  exports.prototype['age_62'] = undefined;
  /**
   * The age 62 tobacco rate for the plan
   * @member {Number} age_62_tobacco
   */
  exports.prototype['age_62_tobacco'] = undefined;
  /**
   * The age 63 non-tobacco rate for the plan
   * @member {Number} age_63
   */
  exports.prototype['age_63'] = undefined;
  /**
   * The age 63 tobacco rate for the plan
   * @member {Number} age_63_tobacco
   */
  exports.prototype['age_63_tobacco'] = undefined;
  /**
   * The age 64 non-tobacco rate for the plan
   * @member {Number} age_64
   */
  exports.prototype['age_64'] = undefined;
  /**
   * The age 64 tobacco rate for the plan
   * @member {Number} age_64_tobacco
   */
  exports.prototype['age_64_tobacco'] = undefined;
  /**
   * The age 65 non-tobacco rate for the plan
   * @member {Number} age_65
   */
  exports.prototype['age_65'] = undefined;
  /**
   * The age 65 tobacco rate for the plan
   * @member {Number} age_65_tobacco
   */
  exports.prototype['age_65_tobacco'] = undefined;



  return exports;
}));


