(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['./ApiClient', './model/Applicant', './model/Base', './model/Carrier', './model/CarrierSubsidiary', './model/County', './model/CountyBulk', './model/Drug', './model/DrugCoverage', './model/DrugCoverageResponse', './model/DrugPackage', './model/DrugSearchResponse', './model/Meta', './model/Plan', './model/PlanCounty', './model/PlanCountyBulk', './model/PlanFindResponse', './model/PlanSearchResult', './model/Pricing', './model/Provider', './model/ProviderResponse', './model/RatingArea', './model/RequestPlanFind', './model/State', './model/ZipCode', './model/ZipCounty', './model/ZipCountyBulk', './model/ZipCountyResponse', './api/DrugsApi', './api/PlansApi', './api/ProvidersApi', './api/ZipCountiesApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Applicant'), require('./model/Base'), require('./model/Carrier'), require('./model/CarrierSubsidiary'), require('./model/County'), require('./model/CountyBulk'), require('./model/Drug'), require('./model/DrugCoverage'), require('./model/DrugCoverageResponse'), require('./model/DrugPackage'), require('./model/DrugSearchResponse'), require('./model/Meta'), require('./model/Plan'), require('./model/PlanCounty'), require('./model/PlanCountyBulk'), require('./model/PlanFindResponse'), require('./model/PlanSearchResult'), require('./model/Pricing'), require('./model/Provider'), require('./model/ProviderResponse'), require('./model/RatingArea'), require('./model/RequestPlanFind'), require('./model/State'), require('./model/ZipCode'), require('./model/ZipCounty'), require('./model/ZipCountyBulk'), require('./model/ZipCountyResponse'), require('./api/DrugsApi'), require('./api/PlansApi'), require('./api/ProvidersApi'), require('./api/ZipCountiesApi'));
  }
}(function(ApiClient, Applicant, Base, Carrier, CarrierSubsidiary, County, CountyBulk, Drug, DrugCoverage, DrugCoverageResponse, DrugPackage, DrugSearchResponse, Meta, Plan, PlanCounty, PlanCountyBulk, PlanFindResponse, PlanSearchResult, Pricing, Provider, ProviderResponse, RatingArea, RequestPlanFind, State, ZipCode, ZipCounty, ZipCountyBulk, ZipCountyResponse, DrugsApi, PlansApi, ProvidersApi, ZipCountiesApi) {
  'use strict';

  /**
   * Autogenerated JavaScript
            client for the Vericred API..<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var vericred-client = require('./index'); // See note below*.
   * var xxxSvc = new vericred-client.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new vericred-client.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['./index'], function(){...}) and put the application logic within the
   * callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new vericred-client.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new vericred-client.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 0.0.2
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Applicant model constructor.
     * @property {module:model/Applicant}
     */
    Applicant: Applicant,
    /**
     * The Base model constructor.
     * @property {module:model/Base}
     */
    Base: Base,
    /**
     * The Carrier model constructor.
     * @property {module:model/Carrier}
     */
    Carrier: Carrier,
    /**
     * The CarrierSubsidiary model constructor.
     * @property {module:model/CarrierSubsidiary}
     */
    CarrierSubsidiary: CarrierSubsidiary,
    /**
     * The County model constructor.
     * @property {module:model/County}
     */
    County: County,
    /**
     * The CountyBulk model constructor.
     * @property {module:model/CountyBulk}
     */
    CountyBulk: CountyBulk,
    /**
     * The Drug model constructor.
     * @property {module:model/Drug}
     */
    Drug: Drug,
    /**
     * The DrugCoverage model constructor.
     * @property {module:model/DrugCoverage}
     */
    DrugCoverage: DrugCoverage,
    /**
     * The DrugCoverageResponse model constructor.
     * @property {module:model/DrugCoverageResponse}
     */
    DrugCoverageResponse: DrugCoverageResponse,
    /**
     * The DrugPackage model constructor.
     * @property {module:model/DrugPackage}
     */
    DrugPackage: DrugPackage,
    /**
     * The DrugSearchResponse model constructor.
     * @property {module:model/DrugSearchResponse}
     */
    DrugSearchResponse: DrugSearchResponse,
    /**
     * The Meta model constructor.
     * @property {module:model/Meta}
     */
    Meta: Meta,
    /**
     * The Plan model constructor.
     * @property {module:model/Plan}
     */
    Plan: Plan,
    /**
     * The PlanCounty model constructor.
     * @property {module:model/PlanCounty}
     */
    PlanCounty: PlanCounty,
    /**
     * The PlanCountyBulk model constructor.
     * @property {module:model/PlanCountyBulk}
     */
    PlanCountyBulk: PlanCountyBulk,
    /**
     * The PlanFindResponse model constructor.
     * @property {module:model/PlanFindResponse}
     */
    PlanFindResponse: PlanFindResponse,
    /**
     * The PlanSearchResult model constructor.
     * @property {module:model/PlanSearchResult}
     */
    PlanSearchResult: PlanSearchResult,
    /**
     * The Pricing model constructor.
     * @property {module:model/Pricing}
     */
    Pricing: Pricing,
    /**
     * The Provider model constructor.
     * @property {module:model/Provider}
     */
    Provider: Provider,
    /**
     * The ProviderResponse model constructor.
     * @property {module:model/ProviderResponse}
     */
    ProviderResponse: ProviderResponse,
    /**
     * The RatingArea model constructor.
     * @property {module:model/RatingArea}
     */
    RatingArea: RatingArea,
    /**
     * The RequestPlanFind model constructor.
     * @property {module:model/RequestPlanFind}
     */
    RequestPlanFind: RequestPlanFind,
    /**
     * The State model constructor.
     * @property {module:model/State}
     */
    State: State,
    /**
     * The ZipCode model constructor.
     * @property {module:model/ZipCode}
     */
    ZipCode: ZipCode,
    /**
     * The ZipCounty model constructor.
     * @property {module:model/ZipCounty}
     */
    ZipCounty: ZipCounty,
    /**
     * The ZipCountyBulk model constructor.
     * @property {module:model/ZipCountyBulk}
     */
    ZipCountyBulk: ZipCountyBulk,
    /**
     * The ZipCountyResponse model constructor.
     * @property {module:model/ZipCountyResponse}
     */
    ZipCountyResponse: ZipCountyResponse,
    /**
     * The DrugsApi service constructor.
     * @property {module:api/DrugsApi}
     */
    DrugsApi: DrugsApi,
    /**
     * The PlansApi service constructor.
     * @property {module:api/PlansApi}
     */
    PlansApi: PlansApi,
    /**
     * The ProvidersApi service constructor.
     * @property {module:api/ProvidersApi}
     */
    ProvidersApi: ProvidersApi,
    /**
     * The ZipCountiesApi service constructor.
     * @property {module:api/ZipCountiesApi}
     */
    ZipCountiesApi: ZipCountiesApi
  };

  return exports;
}));
