(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['./ApiClient', './model/Applicant', './model/Carrier', './model/CarrierSubsidiary', './model/County', './model/Drug', './model/DrugCoverage', './model/InlineResponse200', './model/InlineResponse2001', './model/InlineResponse2002', './model/Plan', './model/PlanCounty', './model/PlanSearchResult', './model/Pricing', './model/Provider', './model/Query', './model/RatingArea', './model/State', './model/ZipCode', './model/ZipCounty', './api/DrugCoverageApi', './api/PlansApi', './api/ProvidersApi', './api/ZipCountiesApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Applicant'), require('./model/Carrier'), require('./model/CarrierSubsidiary'), require('./model/County'), require('./model/Drug'), require('./model/DrugCoverage'), require('./model/InlineResponse200'), require('./model/InlineResponse2001'), require('./model/InlineResponse2002'), require('./model/Plan'), require('./model/PlanCounty'), require('./model/PlanSearchResult'), require('./model/Pricing'), require('./model/Provider'), require('./model/Query'), require('./model/RatingArea'), require('./model/State'), require('./model/ZipCode'), require('./model/ZipCounty'), require('./api/DrugCoverageApi'), require('./api/PlansApi'), require('./api/ProvidersApi'), require('./api/ZipCountiesApi'));
  }
}(function(ApiClient, Applicant, Carrier, CarrierSubsidiary, County, Drug, DrugCoverage, InlineResponse200, InlineResponse2001, InlineResponse2002, Plan, PlanCounty, PlanSearchResult, Pricing, Provider, Query, RatingArea, State, ZipCode, ZipCounty, DrugCoverageApi, PlansApi, ProvidersApi, ZipCountiesApi) {
  'use strict';

  /**
   * Autogenerated JavaScript client for the Vericred API..<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var vericred-client = require('./index'); // See note below*.
   * var xxxSvc = new vericred-client.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new vericred-client.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['./index'], function(){...}) and put the application logic within the
   * callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new vericred-client.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new vericred-client.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 0.0.1
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Applicant model constructor.
     * @property {module:model/Applicant}
     */
    Applicant: Applicant,
    /**
     * The Carrier model constructor.
     * @property {module:model/Carrier}
     */
    Carrier: Carrier,
    /**
     * The CarrierSubsidiary model constructor.
     * @property {module:model/CarrierSubsidiary}
     */
    CarrierSubsidiary: CarrierSubsidiary,
    /**
     * The County model constructor.
     * @property {module:model/County}
     */
    County: County,
    /**
     * The Drug model constructor.
     * @property {module:model/Drug}
     */
    Drug: Drug,
    /**
     * The DrugCoverage model constructor.
     * @property {module:model/DrugCoverage}
     */
    DrugCoverage: DrugCoverage,
    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200: InlineResponse200,
    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001: InlineResponse2001,
    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002: InlineResponse2002,
    /**
     * The Plan model constructor.
     * @property {module:model/Plan}
     */
    Plan: Plan,
    /**
     * The PlanCounty model constructor.
     * @property {module:model/PlanCounty}
     */
    PlanCounty: PlanCounty,
    /**
     * The PlanSearchResult model constructor.
     * @property {module:model/PlanSearchResult}
     */
    PlanSearchResult: PlanSearchResult,
    /**
     * The Pricing model constructor.
     * @property {module:model/Pricing}
     */
    Pricing: Pricing,
    /**
     * The Provider model constructor.
     * @property {module:model/Provider}
     */
    Provider: Provider,
    /**
     * The Query model constructor.
     * @property {module:model/Query}
     */
    Query: Query,
    /**
     * The RatingArea model constructor.
     * @property {module:model/RatingArea}
     */
    RatingArea: RatingArea,
    /**
     * The State model constructor.
     * @property {module:model/State}
     */
    State: State,
    /**
     * The ZipCode model constructor.
     * @property {module:model/ZipCode}
     */
    ZipCode: ZipCode,
    /**
     * The ZipCounty model constructor.
     * @property {module:model/ZipCounty}
     */
    ZipCounty: ZipCounty,
    /**
     * The DrugCoverageApi service constructor.
     * @property {module:api/DrugCoverageApi}
     */
    DrugCoverageApi: DrugCoverageApi,
    /**
     * The PlansApi service constructor.
     * @property {module:api/PlansApi}
     */
    PlansApi: PlansApi,
    /**
     * The ProvidersApi service constructor.
     * @property {module:api/ProvidersApi}
     */
    ProvidersApi: ProvidersApi,
    /**
     * The ZipCountiesApi service constructor.
     * @property {module:api/ZipCountiesApi}
     */
    ZipCountiesApi: ZipCountiesApi
  };

  return exports;
}));
